# Generated by Django 5.1.6 on 2025-05-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20, null=True),
        ),
    ]
