# Generated by Django 5.1.6 on 2025-05-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('return_in_progress', 'Return In Progress'), ('returned', 'Returned'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
