# Generated by Django 5.1.6 on 2025-05-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_delivery_status_booking_is_returned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_returned',
            new_name='is_return',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_requested',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_requested_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='returned_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20, null=True),
        ),
    ]
