# Generated by Django 5.1.6 on 2025-05-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_rename_is_returned_booking_is_return_and_more'),
    ]

    operations = [
    ]
