# Generated by Django 5.1.6 on 2025-05-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_auto_20250513_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_return',
        ),
        migrations.AddField(
            model_name='booking',
            name='return_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('in_return', 'In Return'), ('returned', 'Returned'), ('completed', 'Completed')], default='not_started', max_length=20, null=True),
        ),
    ]
