# Generated by Django 5.1.6 on 2025-05-12 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_remove_booking_is_return_booking_return_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='return_status',
        ),
    ]
