# Generated by Django 5.1.6 on 2025-05-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_remove_booking_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='return_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('in_return', 'In Return'), ('returned', 'Returned'), ('completed', 'Completed')], default='not_started', max_length=20, null=True),
        ),
    ]
