# Generated by Django 5.2 on 2025-05-06 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0015_remove_item_is_rented'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='dispute_evidence/')),
                ('checkout_report', models.TextField()),
                ('return_report', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'Under Investigation'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('outcome', models.CharField(choices=[('none', 'Not Determined'), ('valid', 'Valid Dispute'), ('invalid', 'Invalid Dispute')], default='none', max_length=20)),
                ('at_fault', models.CharField(choices=[('none', 'Not Determined'), ('renter', 'Renter At Fault'), ('owner', 'Owner At Fault'), ('both', 'Both At Fault'), ('neither', 'Neither At Fault')], default='none', max_length=20)),
                ('ai_analysis', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_disputes', to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='items.item')),
            ],
        ),
    ]
