# Generated by Django 5.2.1 on 2025-05-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='clip_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='combined_confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dispute',
            name='damage_progression_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dispute',
            name='image_similarity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
