# Generated by Django 5.2 on 2025-05-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_dispute_clip_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='clip_analysis',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='combined_confidence_score',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='damage_progression_score',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='image_similarity_score',
        ),
    ]
