# Generated by Django 4.2.16 on 2024-11-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_rentee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='rentee',
            new_name='rentee_id',
        ),
    ]
