# Generated by Django 4.2.16 on 2024-11-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_rename_rentee_item_rentee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='rentee_id',
            new_name='rentee',
        ),
    ]
