# Generated by Django 4.2.16 on 2024-12-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_searchhistory_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='item',
            field=models.CharField(max_length=255),
        ),
    ]
