# Generated by Django 4.2.16 on 2024-12-03 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_searchhistory_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
