# Generated by Django 4.2.7 on 2024-12-03 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_searchhistory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='search_query',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
