# Generated by Django 5.1.6 on 2025-02-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_searchhistory_search_query_alter_searchhistory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
