# Generated by Django 5.1.6 on 2025-02-15 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_item_address'),
        ('items', '0013_item_is_rented'),
    ]

    operations = [
    ]
