# Generated by Django 5.1.6 on 2025-02-15 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_merge_0013_item_address_0013_item_is_rented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_rented',
        ),
    ]
