# Generated by Django 5.2 on 2025-05-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='cached_search_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
