# Generated by Django 5.1.6 on 2025-02-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_comment_review_review_review_sentiment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='review',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
