# Generated by Django 5.2 on 2025-05-04 15:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0006_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemConditionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('checkout', 'Checkout'), ('return', 'Return')], max_length=10)),
                ('overall_condition', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout_image', models.ImageField(blank=True, null=True, upload_to='condition_reports/')),
                ('return_image', models.ImageField(blank=True, null=True, upload_to='condition_reports/')),
                ('checkout_damage_location', models.CharField(blank=True, max_length=100)),
                ('checkout_damage_description', models.TextField(blank=True)),
                ('return_damage_location', models.CharField(blank=True, max_length=100)),
                ('return_damage_description', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_condition_reports', to='bookings.booking')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('booking', 'report_type')},
            },
        ),
    ]
