# Generated by Django 5.1.2 on 2025-04-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_type_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fault_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
