# Generated by Django 5.2 on 2025-05-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_fault_count_user_is_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fault_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
    ]
