# Generated by Django 5.2 on 2025-05-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_fault_count_remove_user_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fault_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
